// ============================================================================
// 8 CHAPTERS OF CRITTER PAC-MAZE — EACH CHAPTER USES A DIFFERENT CRITTER HEAD!
// Grid dimensions: 21 columns x 19 rows (symmetric arcade mazes with warp tunnels)
// Legend:
//   '#' = Wall
//   '.' = Chapter Themed Bean (+10 pts)
//   'o' = Chapter Power Pellet (+50 pts, turns Villain Ghosts Frightened!)
//   '-' = Ghost House Door (Ghosts pass through; Critters blocked)
//   'G' = Ghost House Interior (row 11, cols 9..11)
//   'P' = Player Critter Head Spawn (col 10, row 15)
//   ' ' = Empty Tunnel / Warp Corridor
// ============================================================================

export const VILLAINS = [
  { id: 'huggy',     name: 'Huggy Wuggy',     cn: '哈吉瓦吉', icon: 'icons/huggy.jpg',     color: '#3a86ff', scatterTarget: { x: 19, y: 1 } },
  { id: 'mommy',     name: 'Mommy Long Legs', cn: '长腿妈咪', icon: 'icons/mommy.jpg',     color: '#ff5d8f', scatterTarget: { x: 1,  y: 1 } },
  { id: 'pj',        name: 'PJ Pug-a-Pillar', cn: '毛毛虫犬', icon: 'icons/pj.jpg',        color: '#06d6a0', scatterTarget: { x: 19, y: 17 } },
  { id: 'bunzo',     name: 'Bunzo Bunny',     cn: '邦佐兔',   icon: 'icons/bunzo.jpg',     color: '#ff9f1c', scatterTarget: { x: 1,  y: 17 } }
];

export const CHAPTERS = [
  {
    index: 0,
    id: 'dogday',
    critterName: 'DogDay · 日犬',
    chapterTitle: 'CH.1 DOGDAY · 日犬阳光吃豆人',
    chapterSub: 'Sunlit Meadow · 阳光草甸迷宫 (Eat all ☀️ Sun Beans!)',
    icon: 'icons/dogday.jpg',
    ringColor: '#ff9f1c',
    earStyle: 'floppy_dog',
    earColor: '#e85d04',
    floorBg: '#162238',
    wallFill: '#2b580c',
    wallBorder: '#80ed99',
    beanEmoji: '☀️',
    beanName: 'Chomps Golden Sun Beans · 吞吃金阳豆',
    beanColor: '#ffd166',
    beanGlow: '#ff9f1c',
    pelletEmoji: '🌟',
    pelletColor: '#fff3bf',
    fruitEmoji: '🦴',
    skill: {
      id: 'solar_dash',
      name: '☀️ Solar Dash · 阳光冲刺',
      desc: '3.0s blazing speed + solar aura that repels ghosts! · 3秒加速冲刺并免疫反派碰撞！',
      cooldown: 11.0,
      duration: 3.0
    },
    map: [
      '#####################',
      '#o........#........o#',
      '#.###.###.#.###.###.#',
      '#.# #.# #.#.# #.# #.#',
      '#.###.###.#.###.###.#',
      '#...................#',
      '#.###.#.#####.#.###.#',
      '#.....#...#...#.....#',
      '#####.###.#.###.#####',
      '    #...........#    ',
      '#####.#.##-##.#.#####',
      '     ...#GGG#...     ',
      '#####.#.#####.#.#####',
      '    #...........#    ',
      '#####.#.#####.#.#####',
      '#.........P.........#',
      '#.###.###.#.###.###.#',
      '#o..#...........#..o#',
      '#####################'
    ]
  },
  {
    index: 1,
    id: 'catnap',
    critterName: 'CatNap · 瞌睡猫',
    chapterTitle: 'CH.2 CATNAP · 瞌睡猫星月吃豆人',
    chapterSub: 'Moonlit Shrine · 星月神殿迷宫 (Eat all 🌙 Moon Beans!)',
    icon: 'icons/catnap.jpg',
    ringColor: '#b197fc',
    earStyle: 'pointy_cat',
    earColor: '#7950f2',
    floorBg: '#151934',
    wallFill: '#3b28cc',
    wallBorder: '#9775fa',
    beanEmoji: '🌙',
    beanName: 'Chomps Lavender Moon Beans · 吞吃星月豆',
    beanColor: '#e5dbff',
    beanGlow: '#b197fc',
    pelletEmoji: '🔮',
    pelletColor: '#f3d9fa',
    fruitEmoji: '🐟',
    skill: {
      id: 'poppy_slumber',
      name: '💤 Poppy Slumber · 催眠星雾',
      desc: 'Puts all ghosts into deep sleep for 3.5s! · 释放梦境星雾使全场幽灵定身3.5秒！',
      cooldown: 12.0,
      duration: 3.5
    },
    map: [
      '#####################',
      '#o....#.......#....o#',
      '#.###.#.#####.#.###.#',
      '#.# #...........# #.#',
      '#.###.###.#.###.###.#',
      '#.....#...#...#.....#',
      '###.#.#.#####.#.#.###',
      '#...#...........#...#',
      '#.###.###.#.###.###.#',
      '  .................  ',
      '#.###.#.##-##.#.###.#',
      '#...#...#GGG#...#...#',
      '###.#.#.#####.#.#.###',
      '#.....#.......#.....#',
      '#.#####.#####.#####.#',
      '#.........P.........#',
      '#.###.###.#.###.###.#',
      '#o........#........o#',
      '#####################'
    ]
  },
  {
    index: 2,
    id: 'bobby',
    critterName: 'Bobby BearHug · 抱抱熊',
    chapterTitle: 'CH.3 BOBBY BEARHUG · 抱抱熊甜心吃豆人',
    chapterSub: 'Roseberry Garden · 玫瑰甜莓迷宫 (Eat all 🍓 Berry Beans!)',
    icon: 'icons/bobby.jpg',
    ringColor: '#ff6b6b',
    earStyle: 'round_bear',
    earColor: '#e03131',
    floorBg: '#281524',
    wallFill: '#801336',
    wallBorder: '#ff8fab',
    beanEmoji: '🍓',
    beanName: 'Chomps Sweet Berry Beans · 吞吃甜心莓豆',
    beanColor: '#ffc2d1',
    beanGlow: '#ff4d6d',
    pelletEmoji: '💖',
    pelletColor: '#ffe5ec',
    fruitEmoji: '🍯',
    skill: {
      id: 'heart_shield',
      name: '🛡️ Heart Hug Shield · 爱心护盾',
      desc: '4.0s rose bubble shield + pulls nearby beans! · 4秒爱心护盾并吸附周围豆子！',
      cooldown: 11.5,
      duration: 4.0
    },
    map: [
      '#####################',
      '#o..#...........#..o#',
      '#.#.#.####.####.#.#.#',
      '#...................#',
      '#.###.#.#####.#.###.#',
      '#.....#...#...#.....#',
      '#.#####.#.#.#.#####.#',
      '#.......#...#.......#',
      '#####.###.#.###.#####',
      '     ...........     ',
      '#####.#.##-##.#.#####',
      '#.......#GGG#.......#',
      '#.###.#.#####.#.###.#',
      '#...#...........#...#',
      '###.#.#.#####.#.#.###',
      '#.........P.........#',
      '#.####.###.###.####.#',
      '#o.................o#',
      '#####################'
    ]
  },
  {
    index: 3,
    id: 'craftycorn',
    critterName: 'CraftyCorn · 独角兽',
    chapterTitle: 'CH.4 CRAFTYCORN · 独角兽彩虹吃豆人',
    chapterSub: 'Rainbow Canvas · 彩虹画廊迷宫 (Eat all 🎨 Paint Beans!)',
    icon: 'icons/craftycorn.jpg',
    ringColor: '#4cc9f0',
    earStyle: 'unicorn_horn',
    earColor: '#f72585',
    floorBg: '#12263a',
    wallFill: '#006494',
    wallBorder: '#72efdd',
    beanEmoji: '🎨',
    beanName: 'Chomps Rainbow Star Beans · 吞吃彩虹画豆',
    beanColor: '#90e0ef',
    beanGlow: '#4cc9f0',
    pelletEmoji: '💎',
    pelletColor: '#caf0f8',
    fruitEmoji: '🌈',
    skill: {
      id: 'rainbow_fright',
      name: '🌈 Prism Flash · 彩虹炫光',
      desc: 'Turns all ghosts Frightened blue for 4.0s + speed boost! · 炫光使全体幽灵变蓝可吃4秒！',
      cooldown: 14.0,
      duration: 4.0
    },
    map: [
      '#####################',
      '#o........#........o#',
      '#.#####.#.#.#.#####.#',
      '#.......#...#.......#',
      '#.###.#########.###.#',
      '#.#...............#.#',
      '#.#.###.#####.###.#.#',
      '#.....#...#...#.....#',
      '#####.###.#.###.#####',
      '     ...........     ',
      '#####.#.##-##.#.#####',
      '#.......#GGG#.......#',
      '#.#.###.#####.###.#.#',
      '#.#...............#.#',
      '#.###.#########.###.#',
      '#.........P.........#',
      '#.###.###.#.###.###.#',
      '#o....#.......#....o#',
      '#####################'
    ]
  },
  {
    index: 4,
    id: 'hoppy',
    critterName: 'Hoppy Hopscotch · 跳跳兔',
    chapterTitle: 'CH.5 HOPPY · 跳跳兔闪电吃豆人',
    chapterSub: 'Emerald Stadium · 翡翠运动场迷宫 (Eat all 🥕 Carrot Beans!)',
    icon: 'icons/hoppy.jpg',
    ringColor: '#52b788',
    earStyle: 'tall_bunny',
    earColor: '#40916c',
    floorBg: '#132a13',
    wallFill: '#1b4332',
    wallBorder: '#74c69d',
    beanEmoji: '🥕',
    beanName: 'Chomps Crispy Carrot Beans · 吞吃脆脆胡萝卜豆',
    beanColor: '#ff9f1c',
    beanGlow: '#74c69d',
    pelletEmoji: '⚡',
    pelletColor: '#d8f3dc',
    fruitEmoji: '🏅',
    skill: {
      id: 'bunny_turbo',
      name: '🦘 Bunny Overdrive · 闪电兔冲刺',
      desc: '3.5s super hop speed + stuns nearby ghosts! · 3.5秒极速弹跳并震晕身边幽灵！',
      cooldown: 10.5,
      duration: 3.5
    },
    map: [
      '#####################',
      '#o..#.....#.....#..o#',
      '#.#.#.###.#.###.#.#.#',
      '#.#...............#.#',
      '#.###.###.#.###.###.#',
      '#.........#.........#',
      '#.###.#.#####.#.###.#',
      '#.#...#...#...#...#.#',
      '#.#.#####.#.#####.#.#',
      '  .................  ',
      '###.#...##-##...#.###',
      '#.#.....#GGG#.....#.#',
      '#.###.#.#####.#.###.#',
      '#.....#.......#.....#',
      '#.###.###.#.###.###.#',
      '#.........P.........#',
      '#.###.#########.###.#',
      '#o.................o#',
      '#####################'
    ]
  },
  {
    index: 5,
    id: 'picky',
    critterName: 'PickyPiggy · 佩奇猪',
    chapterTitle: 'CH.6 PICKYPIGGY · 佩奇猪美食吃豆人',
    chapterSub: 'Golden Bakery · 黄金甜品屋迷宫 (Eat all 🍎 Apple Beans!)',
    icon: 'icons/picky.jpg',
    ringColor: '#ff85a1',
    earStyle: 'piggy_ears',
    earColor: '#f72585',
    floorBg: '#2b192e',
    wallFill: '#6d23b6',
    wallBorder: '#ff99c8',
    beanEmoji: '🍎',
    beanName: 'Chomps Sweet Apple Beans · 吞吃红苹果豆',
    beanColor: '#ffccd5',
    beanGlow: '#ff758f',
    pelletEmoji: '🍰',
    pelletColor: '#fff0f3',
    fruitEmoji: '🍔',
    skill: {
      id: 'feast_magnet',
      name: '🧲 Gourmet Vacuum · 大胃王吸豆',
      desc: 'Vacuums all beans within 4.2 tiles + +250 Feast Bonus! · 瞬间吸入周围4格内所有豆子！',
      cooldown: 11.0,
      duration: 2.5
    },
    map: [
      '#####################',
      '#o........#........o#',
      '#.###.###.#.###.###.#',
      '#...#...........#...#',
      '###.#.###.#.###.#.###',
      '#.....#...#...#.....#',
      '#.###.#.#####.#.###.#',
      '#.#...............#.#',
      '#.#.#####.#.#####.#.#',
      '  .................  ',
      '###.#...##-##...#.###',
      '#.#.....#GGG#.....#.#',
      '#.###.#.#####.#.###.#',
      '#.....#.......#.....#',
      '#.###.#########.###.#',
      '#.........P.........#',
      '#.###.###.#.###.###.#',
      '#o..#.....#.....#..o#',
      '#####################'
    ]
  },
  {
    index: 6,
    id: 'bubba',
    critterName: 'Bubba Bubbaphant · 聪聪象',
    chapterTitle: 'CH.7 BUBBA · 聪聪象星海吃豆人',
    chapterSub: 'Starlight Observatory · 星海天文台迷宫 (Eat all 🔵 Pearl Beans!)',
    icon: 'icons/bubba.jpg',
    ringColor: '#38bdf8',
    earStyle: 'elephant_ears',
    earColor: '#0284c7',
    floorBg: '#0f172a',
    wallFill: '#1e3a8a',
    wallBorder: '#60a5fa',
    beanEmoji: '🔵',
    beanName: 'Chomps Wisdom Pearl Beans · 吞吃智慧星珠豆',
    beanColor: '#bae6fd',
    beanGlow: '#38bdf8',
    pelletEmoji: '✨',
    pelletColor: '#f0f9ff',
    fruitEmoji: '📘',
    skill: {
      id: 'cryo_nova',
      name: '❄️ Cryo Nova · 寒冰星爆',
      desc: 'Slows all ghosts by 65% for 4.5s + protective barrier! · 全场幽灵减速65%并获得护盾！',
      cooldown: 11.5,
      duration: 4.5
    },
    map: [
      '#####################',
      '#o....#.......#....o#',
      '#.###.#.#####.#.###.#',
      '#...................#',
      '#.###.###.#.###.###.#',
      '#.#...#...#...#...#.#',
      '#.#.#.#.#####.#.#.#.#',
      '#...#...........#...#',
      '#####.###.#.###.#####',
      '     ...........     ',
      '#####.#.##-##.#.#####',
      '#...#...#GGG#...#...#',
      '#.#.#.#.#####.#.#.#.#',
      '#.#...#.......#...#.#',
      '#.###.#########.###.#',
      '#.........P.........#',
      '#.#####.#.#.#.#####.#',
      '#o......#...#......o#',
      '#####################'
    ]
  },
  {
    index: 7,
    id: 'kickin',
    critterName: 'KickinChicken · 酷酷鸡',
    chapterTitle: 'CH.8 KICKIN · 酷酷鸡黄金终章吃豆人',
    chapterSub: 'Neon Arcade Finale · 霓虹终章迷宫 (Eat all ⭐ Star Beans!)',
    icon: 'icons/kickin.jpg',
    ringColor: '#ffd60a',
    earStyle: 'chicken_crest',
    earColor: '#ff006e',
    floorBg: '#1f1638',
    wallFill: '#5a189a',
    wallBorder: '#ffd60a',
    beanEmoji: '⭐',
    beanName: 'Chomps Golden Star Beans · 吞吃黄金星豆',
    beanColor: '#ffea00',
    beanGlow: '#ff9e00',
    pelletEmoji: '🔥',
    pelletColor: '#fff3b0',
    fruitEmoji: '🎸',
    skill: {
      id: 'thunder_shock',
      name: '⚡ Thunder Shock · 雷霆清场',
      desc: 'Zaps nearest ghost back home & scares all ghosts for 3.5s! · 雷击最近幽灵回巢并惊吓全场！',
      cooldown: 12.5,
      duration: 3.5
    },
    map: [
      '#####################',
      '#o..#...........#..o#',
      '#.#.#.###.#.###.#.#.#',
      '#.....#...#...#.....#',
      '#.###.#.#####.#.###.#',
      '#.#...............#.#',
      '#.#.###.#####.###.#.#',
      '#.....#...#...#.....#',
      '#####.###.#.###.#####',
      '     ...........     ',
      '#####.#.##-##.#.#####',
      '#.......#GGG#.......#',
      '#.#.###.#####.###.#.#',
      '#.#...............#.#',
      '#.###.#########.###.#',
      '#.........P.........#',
      '#.###.###.#.###.###.#',
      '#o........#........o#',
      '#####################'
    ]
  }
];
